config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'snippets#index_global'

  ### USERS + SNIPPETS ###
  get '/users/:id/delete' => 'users#confirm_destroy', as: :delete_user
  get '/users/:id/confirm_delete' => 'users#destroy', as: :confirm_delete_user
  get '/snippets' => 'snippets#index_global'
  get '/snippets/:id/delete' => 'snippets#confirm_destroy', as: :delete_snippet
  get '/snippets/:id/confirm_delete' => 'snippets#destroy', as: :confirm_delete_snippet
  resources :users, except: :destroy do
    resources :snippets, only: :index
  end

  # test post snippet
  post '/snippets/new' => 'snippets#create'
  #

  resources :snippets, except: :index
  ### COMMENTS ###
  post '/snippets/:id' => 'comments#create'

  get '/comments/:id' => 'comments#show', as: :comment
  get '/comments/:id/delete' => 'comments#destroy', as: :delete_comment
  # resources :comments

  ### LIKES ###
  get '/like' => 'likes#create'
  get '/unlike' => 'likes#destroy'

  ### SESSIONS ###
  get '/logout' => 'sessions#destroy', as: :logout
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :language, presence: true
  validates :content, presence: true

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :authorize, only: [:new,:create,:edit,:update,:destroy]

  def index
    @user = User.find(params[:user_id])
  end

  def index_global
    @snippets = Snippet.all
  end

  def show
    @snippet = Snippet.find(params[:id])
    @comment = Comment.new


  end

  def new
    puts params
    @snippet = Snippet.new({title: params[:title], language: params[:language], content: params[:content]})
  end

  def create
    @snippet = Snippet.new(snippet_params)
    @snippet.user = current_user
    if @snippet.save
      redirect_to user_path(@snippet.user)
    else
      redirect_to new_snippet_path(snippet_params)
    end
  end

  def edit
    @snippet = Snippet.find(params[:id])
    @language_mode = language_modes.find {|language| language[:language_mode] == @snippet.language}[:language_mode]
    redirect_to root_path unless current_user.id == @snippet.user.id
  end

  def update
    @snippet = Snippet.find(params[:id])
    if current_user.id == @snippet.user.id
      if @snippet.update_attributes(snippet_params)
        redirect_to snippet_path
      else
        redirect_to edit_snippet_path
      end
    end
  end

  def confirm_destroy
    @user= Snippet.find(params[:id]).user
    redirect_to root_path unless current_user.id == Snippet.find(params[:id]).user.id
  end

  def destroy
    @snippet = Snippet.find(params[:id])
    if current_user.id == @snippet.user.id
      @snippet.destroy
      redirect_to user_path(@snippet.user)
    else
      redirect_to root_path
    end
  end

  private
  def snippet_params
    params.require(:snippet).permit(:title,:content,:language)
  end
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/snippets/confirm_destroy.html.erb
<div class="center-confirm">
	<h1>Are you sure?</h1>
	<h2>This code snippet could potentially help solve world hunger.. just saying.</h2>
	<div class="vertical-form-spacer"></div>
	<%= link_to "Cancel", user_path(@user), class: 'btn btn-default' %> <%= link_to 'Delete Snippet', confirm_delete_snippet_path, class: 'btn btn-danger' %>
</div>

app/views/snippets/create.html.erb
<h1>Snippets#create</h1>
<p>Find me in app/views/snippets/create.html.erb</p>

app/views/snippets/destroy.html.erb
<h1>Snippets#destroy</h1>
<p>Find me in app/views/snippets/destroy.html.erb</p>

app/views/snippets/edit.html.erb
<div class="snippet">
    <div class="row">
        <div class="col-md-2 hidden-xs hidden-sm user-editing">
            <div class="useravatar">
                <a href="<%= user_path(current_user.id) %>"><%= image_tag current_user.gravatar_url %></a>
            </div>
            <div class="snippet-meta">
                <%= link_to current_user.username, user_path(current_user.id) %>
            </div>
        </div>
        <div class="col-md-9">

            <div class="row">
                <%= form_for(@snippet, html: {class: 'form-horizontal'}) do |f| %>
                    <div class="form-group">
                        <div class="col-md-10 col-md-offset-2"><h1>Edit Snippet:</h1></div>
                        <%= f.label :title, 'Title', class: 'col-md-2 control-label' %>
                        <div class="col-sm-10">
                            <%= f.text_field :title, value: @snippet.title, class: 'form-control' %><br>
                        </div>
                    </div>
                    <div class="form-group">
                        <%= f.label 'snippet[language', 'Language', class: 'col-md-2 control-label' %>

                        <div class="col-sm-10">
                            <%= select_tag 'snippet[language]', options_for_select(language_modes.collect {|m| [ m[:name],m[:language_mode]] },@language_mode), {class: 'form-control', :prompt => "Select A Language"} %>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10 new-snippet-container">
                            <%= f.text_area :content %>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <%= f.submit 'Update Snippet', class: 'btn btn-success' %>
                            <%= link_to 'Delete', delete_snippet_path, class: 'btn btn-danger' %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

<script>
	$(function(){
		var myTextArea = document.getElementById('snippet_content');
		var $snippetLanguage = $('#snippet_language');
		var myCodeMirror = CodeMirror.fromTextArea(myTextArea, {
			lineNumbers: true,
			theme: 'monokai',
			lineWrapping: true,
			mode: $snippetLanguage.val()
		});
		$snippetLanguage.change(function() {
			myCodeMirror.setOption("mode", $(this).val());
		});
	})
</script>

app/views/snippets/index.html.erb
<h1><%= @user.username %>'s Snippets:</h1>

<% @user.snippets.each do |s| %>
	<hr>
	<h2><%= link_to s.title, snippet_path(s.user.id,s.id) %> (<%= s.language %>)</h2>
	<h3>By: <%= link_to s.user.username, user_path(s.user) %></h3>
	<textarea disabled><%= s.content %></textarea>
	<%= link_to 'Edit Snippet', edit_snippet_path(s.user.id,s.id) %>
<% end %>

app/views/snippets/index_global.html.erb
<% if logged_in? %>
        <h1>Recent Snippets:</h1>
<% else %>
    <div class="jumbotron">
        <h1>Start Snipping!</h1>
        <p>Lint_Up is your personal code snippet repository. Discover, share, and be inspired by simple solutions to complex code problems. So what are you waiting for? Start snipping!</p>
        <p><%= link_to 'Create a Free Account', new_user_path, class: 'btn btn-success btn-md' %> <%= link_to 'Sign In', new_session_path, class: 'btn btn-primary btn-md' %></p>
    </div>
<% end %>

<% @snippets.order("created_at DESC").each do |s| %>
    <div class="snippet">
        <div class="row">
            <div class="col-md-2 hidden-xs hidden-sm user-posted">
                <div class="useravatar">
                    <a href="<%= user_path(s.user) %>"><%= image_tag s.user.gravatar_url %></a>
                </div>
                <small><%= time_ago_in_words(s.created_at) %> ago</small>
                <div>Comments: <%= s.comments.count %></div>
                <div>Likes: <%= s.likes.count %></div>
            </div>
            <div class="col-md-10">
                <h2><%= link_to s.title, snippet_path(s.id) %> <small><%= language_modes.find {|language| language[:language_mode] == s.language}[:name] %></small></h2>
                <textarea disabled id="snippet-<%= s.id %>"><%= s.content %></textarea>
                <% if logged_in? %>
                    <% if current_user.id == s.user.id %>
                        <a href="<%= edit_snippet_path(s.id) %>" class="btn-sm btn-primary">Edit</a>
                    <% else %>
                        <% if current_user.already_likes?(s) %>
                            <%= link_to 'Unlike', {controller: 'likes', action: 'destroy', id: s.id}, class: 'btn-sm btn-default' %>
                        <% else %>
                            <%= link_to 'Like', {controller: 'likes', action: 'create', id: s.id}, class: 'btn-sm btn-success' %>
                        <% end %>
                    <% end %>
                <% end %>
            </div>
        </div>
        <script>
	        $(function(){
		        var textArea = document.getElementById('snippet-<%= s.id %>');
		        var myCodeMirror = CodeMirror.fromTextArea(textArea, {
			        lineNumbers: true,
			        theme: 'monokai',
			        lineWrapping: true,
			        readOnly: true,
			        mode: '<%= s.language %>'
		        });
	        })
        </script>
    </div>
<% end %>

app/views/snippets/new.html.erb
<h1>Create New Snippet:</h1>

<div class="snippet">
    <div class="row">
        <div class="col-md-2 hidden-xs hidden-sm user-creating">
            <div class="useravatar">
                <a href="<%= user_path(current_user.id) %>"><%= image_tag current_user.gravatar_url %></a>
            </div>
            <div class="snippet-meta">
                <%= link_to current_user.username, user_path(current_user.id) %>
            </div>
        </div>
        <div class="col-md-9">
	        <div class="row">
	            <%= form_for(@snippet, url: new_snippet_path, html: {class: 'form-horizontal'}) do |f| %>
		                <div class="form-group">
		                    <%= f.label :title, 'Title', class: 'col-md-2 control-label' %>
		                    <div class="col-sm-10">
		                        <%= f.text_field :title, class: 'form-control' %>
		                    </div>
		                </div>
		                <div class="form-group">
		                    <%= f.label 'snippet[language', 'Language', class: 'col-md-2 control-label' %>

		                    <div class="col-sm-10">

		                        <%= select_tag('snippet[language]', options_for_select(language_modes.collect {|m| [ m[:name],m[:language_mode]] }), {class: 'form-control', :prompt => "Select A Language"}) %>
		                    </div>
		                </div>
		                <div class="form-group">
		                    <div class="col-sm-offset-2 col-sm-10 new-snippet-container">
		                        <%= f.text_area :content %>
		                    </div>
		                </div>
		                <div class="form-group">
		                    <div class="col-sm-offset-2 col-sm-10">
		                        <%= f.submit 'Add Snippet', class: 'btn btn-success' %>
		                    </div>
		                </div>
	            <% end %>
	        </div>
        </div>
    </div>
</div>

<script>
	$(function(){
		var myTextArea = document.getElementById('snippet_content');
		var $snippetLanguage = $('#snippet_language');
		var myCodeMirror = CodeMirror.fromTextArea(myTextArea, {
			lineNumbers: true,
			theme: 'monokai',
			lineWrapping: true,
			mode: $snippetLanguage.val()
		});
		$snippetLanguage.change(function() {
			myCodeMirror.setOption("mode", $(this).val());
		});
	})
</script>

app/views/snippets/show.html.erb
<div class="snippet">
    <div class="row">
        <div class="col-md-2 hidden-xs hidden-sm user-posted">
            <div class="useravatar">
                <a href="<%= user_path(@snippet.user.id) %>"><%= image_tag @snippet.user.gravatar_url %></a>
            </div>
	        <div class="snippet-meta">
	            <%= link_to @snippet.user.username, user_path(@snippet.user.id) %> | <small><%= time_ago_in_words(@snippet.created_at) %> ago</small>
	            <div>Comments: <%= @snippet.comments.count %></div>
	            <div>Likes: <%= @snippet.likes.count %></div>
	        </div>
        </div>
        <div class="col-md-9">
            <h1><%= link_to @snippet.title, snippet_path(@snippet.id) %> <small><%= language_modes.find {|language| language[:language_mode] == @snippet.language}[:name] %></small></h1>
            <textarea disabled id="snippet-<%= @snippet.id %>"><%= @snippet.content %></textarea>
            <% if logged_in? %>
                <% if current_user.id == @snippet.user.id %>
                    <a href="<%= edit_snippet_path(@snippet.id) %>" class="btn-sm btn-primary">Edit</a>
                <% else %>
                    <% if current_user.already_likes?(@snippet) %>
                        <%= link_to 'Unlike', {controller: 'likes', action: 'destroy', id: @snippet.id}, class: 'btn-sm btn-default' %>
                    <% else %>
                        <%= link_to 'Like', {controller: 'likes', action: 'create', id: @snippet.id}, class: 'btn-sm btn-success' %>
                    <% end %>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

<div class="row leave-comment">
	<div class="col-md-3 row-title">
	    <h3>Leave a Comment</h3>
		(Markdown Supported! <i class="glyphicon glyphicon-thumbs-up ml-5"></i>)
	</div>
	<div class="col-md-7">
	    <% if logged_in? %>
	        <%= form_for(@comment, url: snippet_path(@snippet.id)) do |f|%>
	            <%= f.text_area :body %><br>
	            <%= f.submit 'Post Comment', class: 'btn btn-primary' %>
	        <% end %>
	    <% else %>
	        <%= link_to 'Create an account', new_user_path %> to leave comments.
	    <% end %>
	</div>
</div>


<% if @snippet.comments.count > 0 %>
<div class="row previous-comments">
    <div class="col-md-3 row-title">
        <h3>Previous Comments</h3>
    </div>
</div>

<div class="comments">
    <% @snippet.comments.order("created_at DESC").each do |c| %>
        <div class="row comment">
			<div class="col-md-3 align-right">
			    <div class="commenter-avatar pull-right">
			        <a href="<%= user_path(c.user) %>"><%= image_tag c.user.gravatar_url %></a>
			    </div>
			    <div class="commenter-link"><%= link_to c.user.username, user_path(c.user) %></div>
				<small><%= time_ago_in_words(c.created_at) %> ago</small>
			</div>
			<div class="col-md-7">
	            <textarea class="comment-body" disabled><%= c.body %></textarea>
			</div>
	        <div class="col-md-2">
	            <% if current_user == c.user || current_user == @snippet.user %>
			        <a href="<%= delete_comment_path(c, :call_back_url => request.original_url) %>" class=""><i class="glyphicon glyphicon-remove"></i></a>
	            <% end %>
	        </div>
        </div>
    <% end %>
</div>
<% end %>

<script>
	$(function(){
		var myTextArea = document.getElementById('snippet-<%= @snippet.id %>');
		var myCodeMirror = CodeMirror.fromTextArea(myTextArea, {
			lineNumbers: true,
			theme: 'monokai',
			lineWrapping: true,
			readOnly: true,
			mode: '<%= @snippet.language %>'
		});

		$('.comment-body').each(function(i, val){
			var commentRender = CodeMirror.fromTextArea(val, {
				lineNumbers: true,
				lineWrapping: true,
				readOnly: true,
				mode: 'markdown'
			})
		});

		var newComment = document.getElementById('comment_body');
		var commentCodeMirror = CodeMirror.fromTextArea(newComment, {
			lineNumbers: true,
			lineWrapping: true,
			mode: 'markdown',
			theme: 'base16-light'
		});
	})
</script>

app/views/snippets/update.html.erb
<h1>Snippets#update</h1>
<p>Find me in app/views/snippets/update.html.erb</p>