config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'snippets#index_global'

  ### USERS + SNIPPETS ###
  get '/users/:id/delete' => 'users#confirm_destroy', as: :delete_user
  get '/users/:id/confirm_delete' => 'users#destroy', as: :confirm_delete_user
  get '/snippets' => 'snippets#index_global'
  get '/snippets/:id/delete' => 'snippets#confirm_destroy', as: :delete_snippet
  get '/snippets/:id/confirm_delete' => 'snippets#destroy', as: :confirm_delete_snippet
  resources :users, except: :destroy do
    resources :snippets, only: :index
  end

  # test post snippet
  post '/snippets/new' => 'snippets#create'
  #

  resources :snippets, except: :index
  ### COMMENTS ###
  post '/snippets/:id' => 'comments#create'

  get '/comments/:id' => 'comments#show', as: :comment
  get '/comments/:id/delete' => 'comments#destroy', as: :delete_comment
  # resources :comments

  ### LIKES ###
  get '/like' => 'likes#create'
  get '/unlike' => 'likes#destroy'

  ### SESSIONS ###
  get '/logout' => 'sessions#destroy', as: :logout
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :fname, presence: true
  validates :lname, presence: true
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true


  has_many :snippets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def already_likes?(snippet)
    self.likes.where("snippet_id = #{snippet.id}").count > 0
  end

  include Gravtastic
  is_gravtastic :size => 250,
                :default => 'retro'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:new,:create,:show]

  def index
    @users = User.all.order("created_at DESC")

  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path
    else
      flash[:danger] = 'Please confirm your account fields!'
      redirect_to new_user_path
    end
  end

  def edit
    if user_id_is_params_id?
    # if current_user.id.to_s == params[:id].to_s
    @user = User.find(session[:user_id])
    else
      redirect_to root_path
    end

  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path @user
    else
      redirect_to edit_user_path @user
    end
  end

  def confirm_destroy
    redirect_to root_path unless user_id_is_params_id?
  end

  def destroy
    if user_id_is_params_id?
      @user = User.find(params[:id])

      @user.snippets.destroy
      @user.destroy
      redirect_to logout_path
    else
      redirect_to root_path
    end

  end

  private
  def user_params
    params.require(:user).permit(:fname,:lname,:username,:email,:password,:password_confirmation,:github_username)
  end
end

# test change

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/confirm_destroy.html.erb
<div class="center-confirm">
    <h1>Are You Sure You Want To Delete Your Account?</h1>
    <h2>This can't be undone, all your snippets will be lost forever, leaving you sad and snippet-less.</h2>
	<div class="vertical-form-spacer"></div>
    <%= link_to "Cancel", user_path, class: 'btn btn-default' %> <%= link_to 'Delete Account', confirm_delete_user_path, class: 'btn btn-danger' %>
</div>

app/views/users/edit.html.erb
<div class="vertical-form-spacer"></div>
<%= form_for @user, :html => {class: 'new_user form-horizontal'} do |f| %>
    <div class="row"><legend class="col-md-4 col-md-offset-4">Edit Your Account:</legend></div>
    <fieldset>
        <div class="form-group">
            <%= f.label :fname, 'First Name', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :fname, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :lname, 'Last Name', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :lname, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :email, 'Email', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :email, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :github_username, 'GitHub Username', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :github_username, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :username, 'Username', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :username, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :password, 'Password', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.password_field :password, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :password_confirmation, 'Confirm Password', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-5 col-md-offset-4">
                <%= f.submit 'Update', class: 'btn btn-primary' %>
                <%= link_to 'Cancel', user_path, class: 'btn btn-default' %>
                <%= link_to 'Delete Account', delete_user_path, class: 'btn btn-danger pull-right' %>
            </div>
        </div>
    </fieldset>
<% end %>

app/views/users/index.html.erb
<% @users.each do |u| %>
	<div class="user">
		<!--<h3><%= u.username %></h3>-->
		<h3><%= link_to u.username, user_path(u) %></h3>
		<ul>Snippets (<%= u.snippets.count %>):
		    <% u.snippets.each do |s| %>
		        <li><%= s.title %></li>
		    <% end %>
		</ul>
		<% if u.github_username %>
	        <p>Github: <%= link_to "#{u.github_username}", "http://github.com/#{u.github_username}", target: '_blank' %></p>
	    <% end %>
	</div>
<% end %>

app/views/users/new.html.erb
<div class="vertical-form-spacer"></div>
<%= form_for @user, :html => {class: 'new_user form-horizontal'} do |f| %>
    <div class="row"><legend class="col-md-4 col-md-offset-4">Create Account:</legend></div>
    <fieldset>
        <div class="form-group">
            <%= f.label :fname, 'First Name*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :fname, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :lname, 'Last Name*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :lname, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :username, 'Desired Username*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :username, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :github_username, 'GitHub Username (optional)', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :github_username, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :email, 'Email*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :email, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :password, 'Password*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.password_field :password, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :password_confirmation, 'Confirm Password*', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-8 col-md-offset-4">
                <%= f.submit 'Create Account', class: 'btn btn-success' %>
	            <%= link_to 'Already Have Account?', new_session_path, class: 'btn btn-primary' %>
            </div>
        </div>
    </fieldset>
<% end %>

app/views/users/show.html.erb
<div class="card hovercard">
    <div class="card-background">
        <%= image_tag @user.gravatar_url, class: 'card-bkimg' %>
    </div>
	<div class="user-info">
		<div class="row">
			<div class="col-md-2">
			    <div class="useravatar"><a href="http://gravatar.com" target="_blank"><img data-toggle="tooltip" data-placement="right" title="You can change your profile picture at Gravatar.com!" src="<%= @user.gravatar_url %>"></a></div>
			</div>
			<div class="col-md-10">
			    <div class="card-info">
			        <span class="card-title"><%= "#{@user.fname} #{@user.lname}"%></span>
			        <div class="btn-group pull-right" role="group" aria-label="...">
			            <a href="http://github.com/<%= @user.github_username %>" target="_blank" type="button" class="btn-sm btn-default"><i class="glyphicon glyphicon-share"></i> GitHub</a>
			        </div>
				    <div class="user-meta">
				        <h4>Snippets: <%= @user.snippets.count %> | Favorites: <%= @user.likes.count %></h4>
				    </div>
			    </div>
			</div>
		</div>
	</div>
</div>
<div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
    <div class="btn-group" role="group">
        <button type="button" id="tab-snippets" class="btn btn-primary" href="#tab1" data-toggle="tab"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            <div class="hidden-xs"><%= @user.snippets.count %> Snippet<% if @user.snippets.count != 1 %>s<% end %></div>
        </button>
    </div>
    <div class="btn-group" role="group">
        <button type="button" id="tab-favorites" class="btn btn-default" href="#tab2" data-toggle="tab"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
            <div class="hidden-xs"><%= @user.likes.count %> Favorite<% if @user.likes.count != 1 %>s<% end %></div>
        </button>
    </div>
</div>

<div class="well">
    <div class="tab-content">
        <div class="tab-pane fade in active" id="tab1">
	        <% if @user.snippets.count > 0 %>
	            <div class="snippets">
	                <% @user.snippets.order("created_at DESC").each do |s| %>
	                    <div class="snippet">
	                        <div class="row">
		                        <div class="col-md-2 hidden-xs hidden-sm user-posted">
		                            <div class="useravatar">
		                                <%= image_tag @user.gravatar_url %>
		                            </div>
		                            <small><%= time_ago_in_words(s.created_at) %> ago</small>
		                            <div>Comments: <%= s.comments.count %></div>
		                            <div>Likes: <%= s.likes.count %></div>
		                        </div>
		                        <div class="col-md-10">
		                            <h2><%= link_to s.title, snippet_path(s.id) %> <small><%= language_modes.find {|language| language[:language_mode] == s.language}[:name] %></small></h2>
		                            <textarea disabled id="snippet-<%= s.id %>"><%= s.content %></textarea>
		                            <% if logged_in? %>
		                                <% if current_user.id == s.user.id %>
					                        <a href="<%= edit_snippet_path(s.id) %>" class="btn-sm btn-primary">Edit</a>
		                                <% else %>
		                                    <% if current_user.already_likes?(s) %>
		                                        <%= link_to 'Unlike', {controller: 'likes', action: 'destroy', id: s.id}, class: 'btn-sm btn-default' %>
		                                    <% else %>
		                                        <%= link_to 'Like', {controller: 'likes', action: 'create', id: s.id}, class: 'btn-sm btn-success' %>
		                                    <% end %>
		                                <% end %>
		                            <% end %>
		                        </div>
	                        </div>
	                        <script>
		                        $(function(){
			                        var textArea = document.getElementById('snippet-<%= s.id %>');
			                        var myCodeMirror = CodeMirror.fromTextArea(textArea, {
				                        lineNumbers: true,
				                        theme: 'monokai',
				                        lineWrapping: true,
				                        readOnly: true,
				                        mode: '<%= s.language %>'
			                        });
		                        })
	                        </script>
	                    </div>
	                <% end %>
	            </div>
	        <% else %>
                <div class="jumbotron">
                    <h1>Welcome!</h1>
                    <p>It's time to post your first snippet! When you post a code snippet, it'll show up here on your profile.</p>
                    <p><%= link_to 'Add A Snippet!', new_snippet_path, class: 'btn btn-primary btn-lg' %></p>
                </div>
            <% end %>
        </div>
        <div class="tab-pane fade in" id="tab2">
	        <% if @user.likes.count > 0 %>
	            <div class="snippets">
	                <% @user.likes.order("created_at DESC").each do |l| %>
	                    <div class="snippet">
	                        <div class="row">
	                            <div class="col-md-2 hidden-xs hidden-sm user-posted">
	                                <div class="useravatar">
	                                    <%= image_tag l.snippet.user.gravatar_url %>
	                                </div>
	                                <small><%= time_ago_in_words(l.snippet.created_at) %> ago</small>
	                                <div>Comments: <%= l.snippet.comments.count %></div>
	                                <div>Likes: <%= l.snippet.likes.count %></div>
	                            </div>
	                            <div class="col-md-10">
	                                <h2><%= link_to l.snippet.title, snippet_path(l.snippet.id) %> <small><%= language_modes.find {|language| language[:language_mode] == l.snippet.language}[:name] %></small></h2>
	                                <textarea disabled id="liked-snippet-<%= l.snippet.id %>"><%= l.snippet.content %></textarea>
	                                <% if logged_in? %>
	                                    <% if current_user.id == l.snippet.user.id %>
	                                        <%= link_to 'Edit', edit_snippet_path(l.snippet.id), class: 'btn btn-primary' %> <%= link_to 'Delete', delete_snippet_path(s.id), class: 'btn btn-danger' %>
	                                    <% else %>
	                                        <% if current_user.already_likes?(l.snippet) %>
	                                            <%= link_to 'Unlike', {controller: 'likes', action: 'destroy', id: l.snippet.id}, class: 'btn-sm btn-default' %>
	                                            <% else %>
	                                            <%= link_to 'Like', {controller: 'likes', action: 'create', id: l.snippet.id}, class: 'btn-sm btn-success' %>
	                                        <% end %>
	                                    <% end %>
	                                <% end %>
	                            </div>
	                        </div>
	                        <script>
		                        $(function(){
			                        var textArea = document.getElementById('liked-snippet-<%= l.snippet.id %>');
			                        var myCodeMirror = CodeMirror.fromTextArea(textArea, {
				                        lineNumbers: true,
				                        theme: 'monokai',
				                        lineWrapping: true,
				                        readOnly: true,
				                        mode: '<%= l.snippet.language %>'
			                        });
		                        })
	                        </script>
	                    </div>
	                <% end %>
	            </div>
	        <% else %>
                <div class="jumbotron">
                    <h1>Add Some Favorites!</h1>
                    <p>Browse other user's snippets. When you click 'Like' on a snippet, it'll show up here on your favorites tab.</p>
                    <p><%= link_to 'Browse Snippets', root_path, class: 'btn btn-primary btn-lg' %></p>
                </div>
	        <% end %>
        </div>
    </div>
</div>

<script>
	$(function(){
		$(".btn-pref .btn").click(function () {
			$(".btn-pref .btn").removeClass("btn-primary").addClass("btn-default");
			$(this).removeClass("btn-default").addClass("btn-primary");
		});

		$('button[data-toggle="tab"]').on('shown.bs.tab', function () {
			var codeMirrors = document.getElementsByClassName('CodeMirror');
			for(var i = 0; i < codeMirrors.length; i += 1) {
				codeMirrors[i].CodeMirror.refresh();
			}
		})

		$('[data-toggle="tooltip"]').tooltip()
	})
</script>