config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'snippets#index_global'

  ### USERS + SNIPPETS ###
  get '/users/:id/delete' => 'users#confirm_destroy', as: :delete_user
  get '/users/:id/confirm_delete' => 'users#destroy', as: :confirm_delete_user
  get '/snippets' => 'snippets#index_global'
  get '/snippets/:id/delete' => 'snippets#confirm_destroy', as: :delete_snippet
  get '/snippets/:id/confirm_delete' => 'snippets#destroy', as: :confirm_delete_snippet
  resources :users, except: :destroy do
    resources :snippets, only: :index
  end

  # test post snippet
  post '/snippets/new' => 'snippets#create'
  #

  resources :snippets, except: :index
  ### COMMENTS ###
  post '/snippets/:id' => 'comments#create'

  get '/comments/:id' => 'comments#show', as: :comment
  get '/comments/:id/delete' => 'comments#destroy', as: :delete_comment
  # resources :comments

  ### LIKES ###
  get '/like' => 'likes#create'
  get '/unlike' => 'likes#destroy'

  ### SESSIONS ###
  get '/logout' => 'sessions#destroy', as: :logout
  resources :sessions, only: [:new, :create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lintup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>
<body>

    <% flash.each do |key, value| %>
    <div id="flash-container">
        <div class="flash-msg alert alert-<%= key %>"><%= value %></div>
    </div>
    <% end %>


<!-- NavBar -->
	<nav class="navbar navbar-default header-nav navbar-fixed-top">
	    <div class="container">
	        <!-- Brand and toggle get grouped for better mobile display -->
	        <div class="navbar-header">
	            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	                <span class="sr-only">Toggle navigation</span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	            </button>
		        <a class="navbar-brand" href="<%= root_path %>"><%= image_tag "logo.png" %></a>




	        </div>

	        <!-- Collect the nav links, forms, and other content for toggling -->
	        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	            <!--<ul class="nav navbar-nav">
	                <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
	            </ul>-->
	            <ul class="nav navbar-nav navbar-right">

	                <% if logged_in? %>
	                    <li><%= link_to 'Add Snippet', new_snippet_path, class: 'btn-md btn-success' %></li>
	                    <li class="dropdown">
	                        <a href="#" class="dropdown-toggle btn-md btn-primary" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "#{current_user.fname} #{current_user.lname}" %> <span class="caret"></span></a>
	                        <ul class="dropdown-menu">
	                            <li><%= link_to 'Your Profile', user_path(current_user) %></li>
	                            <li><%= link_to 'Account Settings', "/users/#{current_user.id}/edit" %></li>
	                            <li role="separator" class="divider"></li>
	                            <li><%= link_to 'Log Out', logout_path %></li>
	                        </ul>
	                    </li>


	                <% else %>
	                    <li><%= link_to 'Create Account', new_user_url %></li>
	                    <li><%= link_to 'Sign In', new_session_path %></li>
	                <% end %>
	            </ul>
	        </div><!-- /.navbar-collapse -->
	    </div><!-- /.container-fluid -->
	</nav>
	<!---->
	<div class="container">

	    <%= yield %>
	</div>


	<script>
		$(function(){
			$('#flash-container').animate({top:25}).delay(3000).animate({top:-100});
		})
	</script>
</body>
</html>